// Code generated by hertz generator.

package interaction

import (
	"context"
	"errors"
	"log"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	interaction "video-platform/biz/model/interaction"
	"video-platform/biz/service"
	"video-platform/pkg/middleware"
	"video-platform/pkg/parser"
	"video-platform/pkg/response"
)

// VideoLikeAction .
// @router /api/v1/interaction/like [POST]
func VideoLikeAction(ctx context.Context, c *app.RequestContext) {
	var req interaction.VideoLikeActionRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &interaction.VideoLikeActionResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	userIDValue, _ := c.Get(middleware.ContextUserID)
	userID := userIDValue.(uint)

	videoID, err := parser.VideoID(req.VideoId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &interaction.VideoLikeActionResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	if err := service.Interaction.VideoLikeAction(ctx, userID, videoID, req.ActionType); err != nil {
		switch {
		case errors.Is(err, service.ErrVideoNotFound):
			c.JSON(consts.StatusNotFound, &interaction.VideoLikeActionResponse{
				Base: response.Error(response.CodeVideoNotFound),
			})
			return
		case errors.Is(err, service.ErrAlreadyLiked):
			c.JSON(consts.StatusConflict, &interaction.VideoLikeActionResponse{
				Base: response.Error(response.CodeAlreadyLiked),
			})
			return
		case errors.Is(err, service.ErrLikeNotFound):
			c.JSON(consts.StatusNotFound, &interaction.VideoLikeActionResponse{
				Base: response.Error(response.CodeLikeNotFound),
			})
			return
		}

		log.Printf("[互动模块][点赞操作] 操作失败 user_id=%d video_id=%d action_type=%s: %v", userID, videoID, req.ActionType.String(), err)
		c.JSON(consts.StatusInternalServerError, &interaction.VideoLikeActionResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &interaction.VideoLikeActionResponse{
		Base: response.Success("操作成功"),
	})
}

// ListLikedVideos .
// @router /api/v1/interaction/like/list [GET]
func ListLikedVideos(ctx context.Context, c *app.RequestContext) {
	var req interaction.ListLikedVideosRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &interaction.ListLikedVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	userID, err := parser.UserID(req.UserId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &interaction.ListLikedVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	cursor, err := parser.Cursor(req.Cursor)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &interaction.ListLikedVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	data, err := service.Interaction.ListLikedVideos(ctx, userID, cursor, req.Limit)
	if err != nil {
		if errors.Is(err, service.ErrUserNotFound) {
			c.JSON(consts.StatusNotFound, &interaction.ListLikedVideosResponse{
				Base: response.Error(response.CodeUserNotFound),
			})
			return
		}
		log.Printf("[互动模块][点赞视频列表] 查询失败 user_id=%d: %v", userID, err)
		c.JSON(consts.StatusInternalServerError, &interaction.ListLikedVideosResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &interaction.ListLikedVideosResponse{
		Base: response.Success("获取点赞视频列表成功"),
		Data: data,
	})
}

// PublishComment .
// @router /api/v1/interaction/comment [POST]
func PublishComment(ctx context.Context, c *app.RequestContext) {
	var req interaction.PublishCommentRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &interaction.PublishCommentResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	userIDValue, _ := c.Get(middleware.ContextUserID)
	userID := userIDValue.(uint)

	videoID, err := parser.VideoID(req.VideoId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &interaction.PublishCommentResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	if err := service.Interaction.PublishComment(ctx, userID, videoID, req.Content); err != nil {
		switch {
		case errors.Is(err, service.ErrVideoNotFound):
			c.JSON(consts.StatusNotFound, &interaction.PublishCommentResponse{
				Base: response.Error(response.CodeVideoNotFound),
			})
			return
		case errors.Is(err, service.ErrCommentEmpty):
			c.JSON(consts.StatusBadRequest, &interaction.PublishCommentResponse{
				Base: response.Error(response.CodeCommentEmpty),
			})
			return
		case errors.Is(err, service.ErrCommentTooLong):
			c.JSON(consts.StatusBadRequest, &interaction.PublishCommentResponse{
				Base: response.Error(response.CodeCommentTooLong),
			})
			return
		}

		log.Printf("[互动模块][发布评论] 发布失败 user_id=%d video_id=%d: %v", userID, videoID, err)
		c.JSON(consts.StatusInternalServerError, &interaction.PublishCommentResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &interaction.PublishCommentResponse{
		Base: response.Success("发布评论成功"),
	})
}

// ListUserComments .
// @router /api/v1/interaction/comment/list [GET]
func ListUserComments(ctx context.Context, c *app.RequestContext) {
	var req interaction.ListUserCommentsRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &interaction.ListUserCommentsResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	userID, err := parser.UserID(req.UserId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &interaction.ListUserCommentsResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	cursor, err := parser.Cursor(req.Cursor)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &interaction.ListUserCommentsResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	data, err := service.Interaction.ListUserComments(ctx, userID, cursor, req.Limit)
	if err != nil {
		if errors.Is(err, service.ErrUserNotFound) {
			c.JSON(consts.StatusNotFound, &interaction.ListUserCommentsResponse{
				Base: response.Error(response.CodeUserNotFound),
			})
			return
		}
		log.Printf("[互动模块][用户评论列表] 查询失败 user_id=%d: %v", userID, err)
		c.JSON(consts.StatusInternalServerError, &interaction.ListUserCommentsResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &interaction.ListUserCommentsResponse{
		Base: response.Success("获取用户评论列表成功"),
		Data: data,
	})
}

// DeleteComment .
// @router /api/v1/interaction/comment/delete [POST]
func DeleteComment(ctx context.Context, c *app.RequestContext) {
	var req interaction.DeleteCommentRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &interaction.DeleteCommentResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	userIDValue, _ := c.Get(middleware.ContextUserID)
	userID := userIDValue.(uint)

	commentID, err := parser.Cursor(req.CommentId)
	if err != nil || commentID == 0 {
		c.JSON(consts.StatusBadRequest, &interaction.DeleteCommentResponse{
			Base: response.ParamError("comment_id 格式错误"),
		})
		return
	}

	if err := service.Interaction.DeleteComment(ctx, userID, commentID); err != nil {
		switch {
		case errors.Is(err, service.ErrCommentNotFound):
			c.JSON(consts.StatusNotFound, &interaction.DeleteCommentResponse{
				Base: response.Error(response.CodeCommentNotFound),
			})
			return
		case errors.Is(err, service.ErrNoPermission):
			c.JSON(consts.StatusForbidden, &interaction.DeleteCommentResponse{
				Base: response.Error(response.CodeNoPermission),
			})
			return
		}

		log.Printf("[互动模块][删除评论] 删除失败 user_id=%d comment_id=%d: %v", userID, commentID, err)
		c.JSON(consts.StatusInternalServerError, &interaction.DeleteCommentResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &interaction.DeleteCommentResponse{
		Base: response.Success("删除评论成功"),
	})
}
