// Code generated by hertz generator.

package chat

import (
	"github.com/cloudwego/hertz/pkg/app"
	"video-platform/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuth()}
}

func _listchatmessagesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roomsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listchatroomsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _leavechatroomMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _membersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listchatroommembersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _invitechatroommembersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _markchatroomreadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createchatroomMw() []app.HandlerFunc {
	// your code...
	return nil
}
