// Code generated by hertz generator.

package video

import (
	"github.com/cloudwego/hertz/pkg/app"
	"video-platform/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listvideocommentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethotvideosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpublishedvideosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishvideoMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuth()}
}

func _searchvideosMw() []app.HandlerFunc {
	// your code...
	return nil
}
