// Code generated by hertz generator.

package relation

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	relation "video-platform/biz/model/relation"
)

// RelationAction .
// @router /api/v1/relation/action [POST]
func RelationAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req relation.RelationActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(relation.RelationActionResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListFollowings .
// @router /api/v1/relation/following/list [GET]
func ListFollowings(ctx context.Context, c *app.RequestContext) {
	var err error
	var req relation.ListFollowingsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(relation.ListFollowingsResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListFollowers .
// @router /api/v1/relation/follower/list [GET]
func ListFollowers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req relation.ListFollowersRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(relation.ListFollowersResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListFriends .
// @router /api/v1/relation/friend/list [GET]
func ListFriends(ctx context.Context, c *app.RequestContext) {
	var err error
	var req relation.ListFriendsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(relation.ListFriendsResponse)

	c.JSON(consts.StatusOK, resp)
}
