// Code generated by hertz generator.

package chat

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	chat "video-platform/biz/model/chat"
	"video-platform/pkg/response"
)

const chatHTTPNotImplementedMsg = "聊天 HTTP 接口暂未实现"

// CreateChatRoom .
// @router /api/v1/chat/rooms [POST]
func CreateChatRoom(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.CreateChatRoomRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &chat.CreateChatRoomResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	c.JSON(consts.StatusNotImplemented, &chat.CreateChatRoomResponse{
		Base: response.Error(response.CodeInternalError, chatHTTPNotImplementedMsg),
	})
}

// ListChatRooms .
// @router /api/v1/chat/rooms [GET]
func ListChatRooms(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.ListChatRoomsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &chat.ListChatRoomsResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	c.JSON(consts.StatusNotImplemented, &chat.ListChatRoomsResponse{
		Base: response.Error(response.CodeInternalError, chatHTTPNotImplementedMsg),
	})
}

// ListChatMessages .
// @router /api/v1/chat/messages [GET]
func ListChatMessages(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.ListChatMessagesRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &chat.ListChatMessagesResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	c.JSON(consts.StatusNotImplemented, &chat.ListChatMessagesResponse{
		Base: response.Error(response.CodeInternalError, chatHTTPNotImplementedMsg),
	})
}

// ListChatRoomMembers .
// @router /api/v1/chat/rooms/members [GET]
func ListChatRoomMembers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.ListChatRoomMembersRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &chat.ListChatRoomMembersResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	c.JSON(consts.StatusNotImplemented, &chat.ListChatRoomMembersResponse{
		Base: response.Error(response.CodeInternalError, chatHTTPNotImplementedMsg),
	})
}

// InviteChatRoomMembers .
// @router /api/v1/chat/rooms/members/invite [POST]
func InviteChatRoomMembers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.InviteChatRoomMembersRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &chat.InviteChatRoomMembersResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	c.JSON(consts.StatusNotImplemented, &chat.InviteChatRoomMembersResponse{
		Base: response.Error(response.CodeInternalError, chatHTTPNotImplementedMsg),
	})
}

// LeaveChatRoom .
// @router /api/v1/chat/rooms/leave [POST]
func LeaveChatRoom(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.LeaveChatRoomRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &chat.LeaveChatRoomResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	c.JSON(consts.StatusNotImplemented, &chat.LeaveChatRoomResponse{
		Base: response.Error(response.CodeInternalError, chatHTTPNotImplementedMsg),
	})
}

// MarkChatRoomRead .
// @router /api/v1/chat/rooms/read [POST]
func MarkChatRoomRead(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.MarkChatRoomReadRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &chat.MarkChatRoomReadResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	c.JSON(consts.StatusNotImplemented, &chat.MarkChatRoomReadResponse{
		Base: response.Error(response.CodeInternalError, chatHTTPNotImplementedMsg),
	})
}
