// Code generated by hertz generator.

package video

import (
	"context"
	"errors"
	"log"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	video "video-platform/biz/model/video"
	"video-platform/biz/service"
	"video-platform/pkg/middleware"
	"video-platform/pkg/parser"
	"video-platform/pkg/response"
)

// PublishVideo .
// @router /api/v1/video/publish [POST]
func PublishVideo(ctx context.Context, c *app.RequestContext) {
	var req video.PublishVideoRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &video.PublishVideoResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	userIDValue, _ := c.Get(middleware.ContextUserID)
	userID := userIDValue.(uint)

	videoFile, err := c.FormFile("video")
	if err != nil {
		c.JSON(consts.StatusBadRequest, &video.PublishVideoResponse{
			Base: response.Error(response.CodeVideoFileRequired),
		})
		return
	}

	coverFile, _ := c.FormFile("cover")

	if err := service.Video.PublishVideo(ctx, userID, req.Title, req.Description, videoFile, coverFile); err != nil {
		switch {
		case errors.Is(err, service.ErrUserNotFound):
			c.JSON(consts.StatusNotFound, &video.PublishVideoResponse{
				Base: response.Error(response.CodeUserNotFound),
			})
			return
		case errors.Is(err, service.ErrVideoTitleRequired):
			c.JSON(consts.StatusBadRequest, &video.PublishVideoResponse{
				Base: response.Error(response.CodeVideoTitleRequired),
			})
			return
		case errors.Is(err, service.ErrVideoFileRequired):
			c.JSON(consts.StatusBadRequest, &video.PublishVideoResponse{
				Base: response.Error(response.CodeVideoFileRequired),
			})
			return
		case errors.Is(err, service.ErrUnsupportedVideoExt):
			c.JSON(consts.StatusBadRequest, &video.PublishVideoResponse{
				Base: response.Error(response.CodeUnsupportedVideoType),
			})
			return
		case errors.Is(err, service.ErrUnsupportedVideoCoverExt):
			c.JSON(consts.StatusBadRequest, &video.PublishVideoResponse{
				Base: response.Error(response.CodeUnsupportedCoverType),
			})
			return
		}

		log.Printf("[视频模块][发布视频] 发布失败 user_id=%d title=%s filename=%s: %v", userID, req.Title, videoFile.Filename, err)
		c.JSON(consts.StatusInternalServerError, &video.PublishVideoResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &video.PublishVideoResponse{
		Base: response.Success("发布视频成功"),
	})
}

// ListPublishedVideos .
// @router /api/v1/video/list [GET]
func ListPublishedVideos(ctx context.Context, c *app.RequestContext) {
	var req video.ListPublishedVideosRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &video.ListPublishedVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	userID, err := parser.UserID(req.UserId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &video.ListPublishedVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	cursor, err := parser.Cursor(req.Cursor)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &video.ListPublishedVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	data, err := service.Video.ListPublishedVideos(ctx, userID, cursor, req.Limit)
	if err != nil {
		if errors.Is(err, service.ErrUserNotFound) {
			c.JSON(consts.StatusNotFound, &video.ListPublishedVideosResponse{
				Base: response.Error(response.CodeUserNotFound),
			})
			return
		}
		if errors.Is(err, service.ErrVideoCursorInvalid) {
			c.JSON(consts.StatusBadRequest, &video.ListPublishedVideosResponse{
				Base: response.ParamError(err.Error()),
			})
			return
		}
		log.Printf("[视频模块][用户视频列表] 查询失败 user_id=%d: %v", userID, err)
		c.JSON(consts.StatusInternalServerError, &video.ListPublishedVideosResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &video.ListPublishedVideosResponse{
		Base: response.Success("获取发布视频列表成功"),
		Data: data,
	})
}

// SearchVideos .
// @router /api/v1/video/search [GET]
func SearchVideos(ctx context.Context, c *app.RequestContext) {
	var req video.SearchVideosRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &video.SearchVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	cursor, err := parser.Cursor(req.Cursor)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &video.SearchVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	data, err := service.Video.SearchVideos(ctx, &req, cursor)
	if err != nil {
		if errors.Is(err, service.ErrVideoCursorInvalid) {
			c.JSON(consts.StatusBadRequest, &video.SearchVideosResponse{
				Base: response.ParamError(err.Error()),
			})
			return
		}
		log.Printf("[视频模块][搜索视频] 查询失败 keywords=%s username=%s: %v", req.Keywords, req.Username, err)
		c.JSON(consts.StatusInternalServerError, &video.SearchVideosResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &video.SearchVideosResponse{
		Base: response.Success("搜索视频成功"),
		Data: data,
	})
}

// ListVideoComments .
// @router /api/v1/video/comments [GET]
func ListVideoComments(ctx context.Context, c *app.RequestContext) {
	var req video.ListVideoCommentsRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &video.ListVideoCommentsResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	videoID, err := parser.VideoID(req.VideoId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &video.ListVideoCommentsResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	cursor, err := parser.Cursor(req.Cursor)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &video.ListVideoCommentsResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	data, err := service.Video.ListVideoComments(ctx, videoID, cursor, req.Limit)
	if err != nil {
		if errors.Is(err, service.ErrVideoNotFound) {
			c.JSON(consts.StatusNotFound, &video.ListVideoCommentsResponse{
				Base: response.Error(response.CodeVideoNotFound),
			})
			return
		}
		log.Printf("[视频模块][视频评论列表] 查询失败 video_id=%d: %v", videoID, err)
		c.JSON(consts.StatusInternalServerError, &video.ListVideoCommentsResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &video.ListVideoCommentsResponse{
		Base: response.Success("获取视频评论列表成功"),
		Data: data,
	})
}

// GetHotVideos .
// @router /api/v1/video/hot [GET]
func GetHotVideos(ctx context.Context, c *app.RequestContext) {
	var req video.GetHotVideosRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &video.GetHotVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	cursor, err := parser.ParseHotVideoCursor(req.Cursor)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &video.GetHotVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	data, err := service.Video.GetHotVideos(ctx, cursor, req.Limit)
	if err != nil {
		log.Printf("[视频模块][热门视频] 查询失败: %v", err)
		c.JSON(consts.StatusInternalServerError, &video.GetHotVideosResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &video.GetHotVideosResponse{
		Base: response.Success("获取热门视频成功"),
		Data: data,
	})
}
