// Code generated by hertz generator.

package user

import (
	"context"
	"errors"
	"log"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "video-platform/biz/model/user"
	"video-platform/biz/service"
	"video-platform/pkg/middleware"
	"video-platform/pkg/parser"
	"video-platform/pkg/response"
	"video-platform/pkg/upload"
)

// Register .
// @router /api/v1/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.RegisterResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	err = service.Register(ctx, req.Username, req.Password)
	if err != nil {
		if errors.Is(err, service.ErrUserExists) {
			c.JSON(consts.StatusConflict, &user.RegisterResponse{
				Base: response.Error(response.CodeUserExists),
			})
			return
		}
		log.Printf("[用户模块][注册] 注册用户失败 username=%s: %v", req.Username, err)
		c.JSON(consts.StatusInternalServerError, &user.RegisterResponse{
			Base: response.InternalError(),
		})
		return
	}

	resp := &user.RegisterResponse{
		Base: response.Success("注册用户成功"),
	}
	c.JSON(consts.StatusOK, resp)
}

// Login .
// @router /api/v1/user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.LoginResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	accessToken, refreshToken, err := service.Login(ctx, req.Username, req.Password)
	if err != nil {
		if errors.Is(err, service.ErrUserNotFound) {
			c.JSON(consts.StatusNotFound, &user.LoginResponse{
				Base: response.Error(response.CodeUserNotFound),
			})
			return
		}
		if errors.Is(err, service.ErrPasswordWrong) {
			c.JSON(consts.StatusUnauthorized, &user.LoginResponse{
				Base: response.Error(response.CodePasswordWrong),
			})
			return
		}
		log.Printf("[用户模块][登录] 登录失败 username=%s: %v", req.Username, err)
		c.JSON(consts.StatusInternalServerError, &user.LoginResponse{
			Base: response.InternalError(),
		})
		return
	}

	resp := &user.LoginResponse{
		Base:         response.Success("登录成功"),
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
	}
	c.JSON(consts.StatusOK, resp)
}

// RefreshToken .
// @router /api/v1/user/refresh [POST]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RefreshTokenRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.RefreshTokenResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	accessToken, refreshToken, err := service.RefreshToken(ctx, req.RefreshToken)
	if err != nil {
		if errors.Is(err, service.ErrTokenExpired) {
			c.JSON(consts.StatusUnauthorized, &user.RefreshTokenResponse{
				Base: response.Error(response.CodeTokenExpired),
			})
			return
		}
		if errors.Is(err, service.ErrTokenInvalid) {
			c.JSON(consts.StatusUnauthorized, &user.RefreshTokenResponse{
				Base: response.Error(response.CodeTokenInvalid),
			})
			return
		}
		log.Printf("[用户模块][刷新令牌] 刷新失败: %v", err)
		c.JSON(consts.StatusInternalServerError, &user.RefreshTokenResponse{
			Base: response.InternalError(),
		})
		return
	}

	resp := &user.RefreshTokenResponse{
		Base:         response.Success("刷新成功"),
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
	}
	c.JSON(consts.StatusOK, resp)
}

// GetUserInfo .
// @router /api/v1/user/info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.GetUserInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.GetUserInfoResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	userID, err := parser.UserID(req.UserId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.GetUserInfoResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	userInfo, err := service.GetUserInfo(ctx, userID)
	if err != nil {
		if errors.Is(err, service.ErrUserNotFound) {
			c.JSON(consts.StatusNotFound, &user.GetUserInfoResponse{
				Base: response.Error(response.CodeUserNotFound),
			})
			return
		}
		log.Printf("[用户模块][获取用户信息] 查询失败 user_id=%d: %v", userID, err)
		c.JSON(consts.StatusInternalServerError, &user.GetUserInfoResponse{
			Base: response.InternalError(),
		})
		return
	}

	resp := &user.GetUserInfoResponse{
		Base: response.Success("获取用户信息成功"),
		Data: userInfo,
	}
	c.JSON(consts.StatusOK, resp)
}

// UploadAvatar .
// @router /api/v1/user/avatar [POST]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	userIDValue, ok := c.Get(middleware.ContextUserID)
	if !ok {
		c.JSON(consts.StatusUnauthorized, &user.UploadAvatarResponse{
			Base: response.Unauthorized("未登录或登录已失效"),
		})
		return
	}

	userID, ok := userIDValue.(uint)
	if !ok {
		c.JSON(consts.StatusUnauthorized, &user.UploadAvatarResponse{
			Base: response.Unauthorized("无效的用户身份"),
		})
		return
	}

	file, err := c.FormFile("avatar")
	if err != nil {
		c.JSON(consts.StatusBadRequest, &user.UploadAvatarResponse{
			Base: response.ParamError("缺少头像文件 avatar"),
		})
		return
	}

	savePath, avatarURL, err := upload.PrepareAvatar(userID, file.Filename)
	if err != nil {
		if errors.Is(err, upload.ErrUnsupportedAvatarExt) {
			c.JSON(consts.StatusBadRequest, &user.UploadAvatarResponse{
				Base: response.Error(response.CodeUnsupportedAvatarType),
			})
			return
		}
		log.Printf("[用户模块][上传头像] 准备头像上传失败 user_id=%d filename=%s: %v", userID, file.Filename, err)
		c.JSON(consts.StatusInternalServerError, &user.UploadAvatarResponse{
			Base: response.InternalError(),
		})
		return
	}

	if err := c.SaveUploadedFile(file, savePath); err != nil {
		log.Printf("[用户模块][上传头像] 保存头像失败 user_id=%d filename=%s: %v", userID, file.Filename, err)
		c.JSON(consts.StatusInternalServerError, &user.UploadAvatarResponse{
			Base: response.InternalError(),
		})
		return
	}

	err = service.UpdateUserAvatar(ctx, userID, avatarURL)
	if err != nil {
		if errors.Is(err, service.ErrUserNotFound) {
			c.JSON(consts.StatusNotFound, &user.UploadAvatarResponse{
				Base: response.Error(response.CodeUserNotFound),
			})
			return
		}
		log.Printf("[用户模块][上传头像] 更新头像地址失败 user_id=%d avatar_url=%s: %v", userID, avatarURL, err)
		c.JSON(consts.StatusInternalServerError, &user.UploadAvatarResponse{
			Base: response.InternalError(),
		})
		return
	}

	resp := &user.UploadAvatarResponse{
		Base: response.Success("上传头像成功"),
	}
	c.JSON(consts.StatusOK, resp)
}
