// Code generated by hertz generator.

package platform

import (
	"github.com/cloudwego/hertz/pkg/app"
	"video-platform/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuth()}
}

func _getuserinfoMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuth()}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}
