// Code generated by hertz generator.

package platform

import (
	"context"
	"errors"
	"log"

	"video-platform/biz/model/platform"
	v1 "video-platform/biz/model/platform"
	"video-platform/biz/service"
	"video-platform/pkg/response"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /api/v1/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req platform.RegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &v1.RegisterResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	err = service.Register(ctx, req.Username, req.Password)
	if err != nil {
		if errors.Is(err, service.ErrUserExists) {
			c.JSON(consts.StatusConflict, &v1.RegisterResponse{
				Base: response.Error(response.CodeUserExists),
			})
			return
		}
		log.Printf("[用户模块][注册] 创建用户失败 username=%s: %v", req.Username, err)
		c.JSON(consts.StatusInternalServerError, &v1.RegisterResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &v1.RegisterResponse{
		Base: response.Success(),
	})
}

// Login .
// @router /api/v1/user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req platform.LoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(platform.LoginResponse)

	c.JSON(consts.StatusOK, resp)
}

// RefreshToken .
// @router /api/v1/user/refresh [POST]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	var err error
	var req platform.RefreshTokenRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(platform.RefreshTokenResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetUserInfo .
// @router /api/v1/user/info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req platform.GetUserInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(platform.GetUserInfoResponse)

	c.JSON(consts.StatusOK, resp)
}

// UploadAvatar .
// @router /api/v1/user/avatar [POST]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	var err error
	var req platform.UploadAvatarRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(platform.UploadAvatarResponse)

	c.JSON(consts.StatusOK, resp)
}
