// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	relation "video-platform/biz/router/relation"
	user "video-platform/biz/router/user"
	video "video-platform/biz/router/video"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	video.Register(r)

	user.Register(r)

	relation.Register(r)
}
