// Code generated by hertz generator.

package relation

import (
	"github.com/cloudwego/hertz/pkg/app"
	"video-platform/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationactionMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuth()}
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfollowersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfollowingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfriendsMw() []app.HandlerFunc {
	return []app.HandlerFunc{middleware.JWTAuth()}
}
